version: "3.8"

services:
  backend:
    build: ./backend
    container_name: skilllinkr-backend
    restart: unless-stopped
    networks:
      - app-network
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - skilllinkr_db:/app/db

  caddy:
    image: caddy:2-alpine
    container_name: skilllinkr-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend
    environment:
      - DOMAIN=skilllinkr.ngarikev.tech

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
  skilllinkr_db:
