version: "3.8"

services:
  backend:
    build: ./backend
    container_name: skilllinkr-backend
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=main.py
    networks:
      - app-network

  caddy:
    image: caddy:2-alpine
    container_name: skilllinkr-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/dist:/srv
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
