name: CI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: COPY FILES TO SERVER
        uses: appleboy/scp-action@master
        with:
          host: 34.227.105.106
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: ".,!.git/*"
          target: "~/SkillLinkr"

      - name: BUILD APP, SETUP BACKUP SCRIPT, AND RUN IN SERVER
        uses: appleboy/ssh-action@master
        with:
          host: 34.227.105.106
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd SkillLinkr
            docker compose down
            docker compose build --no-cache
            docker compose up -d
